name = 'Wings'
license = 'MIT'
licenselink = 'https://github.com/icarochiabai/wings/blob/main/LICENSE'
description = "All you need, lightweight, minimalistic Hugo theme that doesn't sacrifice on its looks."

# The home page of the theme, where the source can be found
homepage = 'https://github.com/icarochiabai/wings'

# If you have a running demo of the theme
demosite = 'https://icarochiabai.github.io/'

[author]
  name = 'archicarus'
  homepage = 'icarochiabai.github.io/'
